create table REGIONI
(
    CODICE_REGIONE        NUMBER       not null,
    DENOMINAZIONE_REGIONE VARCHAR2(21) not null,
    STATO                 VARCHAR2(3)  not null,
                                       references STATI
                                           on delete cascade,
    constraint REGIONI_PK
        primary key (CODICE_REGIONE, DENOMINAZIONE_REGIONE)
);

INSERT INTO REGIONI (CODICE_REGIONE, DENOMINAZIONE_REGIONE, STATO) VALUES (1, 'Piemonte', 'ITA');
INSERT INTO REGIONI (CODICE_REGIONE, DENOMINAZIONE_REGIONE, STATO) VALUES (19, 'Sicilia', 'ITA');
INSERT INTO REGIONI (CODICE_REGIONE, DENOMINAZIONE_REGIONE, STATO) VALUES (8, 'Emilia-Romagna', 'ITA');
INSERT INTO REGIONI (CODICE_REGIONE, DENOMINAZIONE_REGIONE, STATO) VALUES (7, 'Liguria', 'ITA');
INSERT INTO REGIONI (CODICE_REGIONE, DENOMINAZIONE_REGIONE, STATO) VALUES (2, 'Valle d''Aosta', 'ITA');
INSERT INTO REGIONI (CODICE_REGIONE, DENOMINAZIONE_REGIONE, STATO) VALUES (17, 'Basilicata', 'ITA');
INSERT INTO REGIONI (CODICE_REGIONE, DENOMINAZIONE_REGIONE, STATO) VALUES (14, 'Molise', 'ITA');
INSERT INTO REGIONI (CODICE_REGIONE, DENOMINAZIONE_REGIONE, STATO) VALUES (15, 'Campania', 'ITA');
INSERT INTO REGIONI (CODICE_REGIONE, DENOMINAZIONE_REGIONE, STATO) VALUES (6, 'Friuli Venezia Giulia', 'ITA');
INSERT INTO REGIONI (CODICE_REGIONE, DENOMINAZIONE_REGIONE, STATO) VALUES (4, 'P.A. Bolzano', 'ITA');
INSERT INTO REGIONI (CODICE_REGIONE, DENOMINAZIONE_REGIONE, STATO) VALUES (16, 'Puglia', 'ITA');
INSERT INTO REGIONI (CODICE_REGIONE, DENOMINAZIONE_REGIONE, STATO) VALUES (20, 'Sardegna', 'ITA');
INSERT INTO REGIONI (CODICE_REGIONE, DENOMINAZIONE_REGIONE, STATO) VALUES (12, 'Lazio', 'ITA');
INSERT INTO REGIONI (CODICE_REGIONE, DENOMINAZIONE_REGIONE, STATO) VALUES (3, 'Lombardia', 'ITA');
INSERT INTO REGIONI (CODICE_REGIONE, DENOMINAZIONE_REGIONE, STATO) VALUES (11, 'Marche', 'ITA');
INSERT INTO REGIONI (CODICE_REGIONE, DENOMINAZIONE_REGIONE, STATO) VALUES (10, 'Umbria', 'ITA');
INSERT INTO REGIONI (CODICE_REGIONE, DENOMINAZIONE_REGIONE, STATO) VALUES (5, 'Veneto', 'ITA');
INSERT INTO REGIONI (CODICE_REGIONE, DENOMINAZIONE_REGIONE, STATO) VALUES (13, 'Abruzzo', 'ITA');
INSERT INTO REGIONI (CODICE_REGIONE, DENOMINAZIONE_REGIONE, STATO) VALUES (18, 'Calabria', 'ITA');
INSERT INTO REGIONI (CODICE_REGIONE, DENOMINAZIONE_REGIONE, STATO) VALUES (9, 'Toscana', 'ITA');
INSERT INTO REGIONI (CODICE_REGIONE, DENOMINAZIONE_REGIONE, STATO) VALUES (4, 'P.A. Trento', 'ITA');