ALTER TABLE STATI ADD
    Capitale VARCHAR(150);

UPDATE STATI SET Capitale = 'Kabul' WHERE DESCRIZIONE= 'Afghanistan';
UPDATE STATI SET Capitale = 'Tirana' WHERE DESCRIZIONE= 'Albania';
UPDATE STATI SET Capitale = 'Algeri' WHERE DESCRIZIONE= 'Algeria';
UPDATE STATI SET Capitale = 'Andorra la Vella' WHERE DESCRIZIONE= 'Andorra';
UPDATE STATI SET Capitale = 'Luanda' WHERE DESCRIZIONE= 'Angola';
UPDATE STATI SET Capitale = 'Saint John''s' WHERE DESCRIZIONE= 'Antigua e Barbuda';
UPDATE STATI SET Capitale = 'Riyād' WHERE DESCRIZIONE= 'Arabia Saudita';
UPDATE STATI SET Capitale = 'Buenos Aires' WHERE DESCRIZIONE= 'Argentina';
UPDATE STATI SET Capitale = 'Erevan' WHERE DESCRIZIONE= 'Armenia';
UPDATE STATI SET Capitale = 'Canberra' WHERE DESCRIZIONE= 'Australia';
UPDATE STATI SET Capitale = 'Vienna' WHERE DESCRIZIONE= 'Austria';
UPDATE STATI SET Capitale = 'Baku' WHERE DESCRIZIONE= 'Azerbaigian';
UPDATE STATI SET Capitale = 'Nassau' WHERE DESCRIZIONE= 'Bahamas';
UPDATE STATI SET Capitale = 'Manama' WHERE DESCRIZIONE= 'Bahrein';
UPDATE STATI SET Capitale = 'Dacca' WHERE DESCRIZIONE= 'Bangladesh';
UPDATE STATI SET Capitale = 'Bridgetown' WHERE DESCRIZIONE= 'Barbados';
UPDATE STATI SET Capitale = 'Bruxelles' WHERE DESCRIZIONE= 'Belgio';
UPDATE STATI SET Capitale = 'Belmopan' WHERE DESCRIZIONE= 'Belize';
UPDATE STATI SET Capitale = 'Porto-Novo' WHERE DESCRIZIONE= 'Benin';
UPDATE STATI SET Capitale = 'Thimphu' WHERE DESCRIZIONE= 'Bhutan';
UPDATE STATI SET Capitale = 'Minsk' WHERE DESCRIZIONE= 'Bielorussia';
UPDATE STATI SET Capitale = 'Naypyidaw' WHERE DESCRIZIONE= 'Birmania';
UPDATE STATI SET Capitale = 'Sucre (legislativa) - La Paz (governativa)' WHERE DESCRIZIONE= 'Bolivia';
UPDATE STATI SET Capitale = 'Sarajevo' WHERE DESCRIZIONE= 'Bosnia ed Erzegovina';
UPDATE STATI SET Capitale = 'Gaborone' WHERE DESCRIZIONE= 'Botswana';
UPDATE STATI SET Capitale = 'Brasilia' WHERE DESCRIZIONE= 'Brasile';
UPDATE STATI SET Capitale = 'Bandar Seri Begawan' WHERE DESCRIZIONE= 'Brunei';
UPDATE STATI SET Capitale = 'Sofia' WHERE DESCRIZIONE= 'Bulgaria';
UPDATE STATI SET Capitale = 'Ouagadougou' WHERE DESCRIZIONE= 'Burkina Faso';
UPDATE STATI SET Capitale = 'Gitega' WHERE DESCRIZIONE= 'Burundi';
UPDATE STATI SET Capitale = 'Phnom Penh' WHERE DESCRIZIONE= 'Cambogia';
UPDATE STATI SET Capitale = 'Yaoundé' WHERE DESCRIZIONE= 'Camerun';
UPDATE STATI SET Capitale = 'Ottawa' WHERE DESCRIZIONE= 'Canada';
UPDATE STATI SET Capitale = 'Praia' WHERE DESCRIZIONE= 'Capo Verde';
UPDATE STATI SET Capitale = 'N''Djamena' WHERE DESCRIZIONE= 'Ciad';
UPDATE STATI SET Capitale = 'Santiago del Cile' WHERE DESCRIZIONE= 'Cile';
UPDATE STATI SET Capitale = 'Pechino' WHERE DESCRIZIONE= 'Cina';
UPDATE STATI SET Capitale = 'Nicosia' WHERE DESCRIZIONE= 'Cipro';
UPDATE STATI SET Capitale = 'Città del Vaticano (città-DESCRIZIONE)' WHERE DESCRIZIONE= 'Città del Vaticano';
UPDATE STATI SET Capitale = 'Bogotà' WHERE DESCRIZIONE= 'Colombia';
UPDATE STATI SET Capitale = 'Moroni' WHERE DESCRIZIONE= 'Comore';
UPDATE STATI SET Capitale = 'Brazzaville' WHERE DESCRIZIONE= 'Repubblica del Congo';
UPDATE STATI SET Capitale = 'Kinshasa' WHERE DESCRIZIONE= 'Repubblica Democratica del Congo';
UPDATE STATI SET Capitale = 'Pyongyang' WHERE DESCRIZIONE= 'Corea del Nord';
UPDATE STATI SET Capitale = 'Seul' WHERE DESCRIZIONE= 'Corea del Sud';
UPDATE STATI SET Capitale = 'Yamoussoukro' WHERE DESCRIZIONE= 'Costa d''Avorio';
UPDATE STATI SET Capitale = 'San Josè' WHERE DESCRIZIONE= 'Costa Rica';
UPDATE STATI SET Capitale = 'Zagabria' WHERE DESCRIZIONE= 'Croazia';
UPDATE STATI SET Capitale = 'L''Avana' WHERE DESCRIZIONE= 'Cuba';
UPDATE STATI SET Capitale = 'Copenaghen' WHERE DESCRIZIONE= 'Danimarca';
UPDATE STATI SET Capitale = 'Roseau' WHERE DESCRIZIONE= 'Dominica';
UPDATE STATI SET Capitale = 'Quito' WHERE DESCRIZIONE= 'Ecuador';
UPDATE STATI SET Capitale = 'Il Cairo' WHERE DESCRIZIONE= 'Egitto';
UPDATE STATI SET Capitale = 'San Salvador' WHERE DESCRIZIONE= 'El Salvador';
UPDATE STATI SET Capitale = 'Abu Dhabi' WHERE DESCRIZIONE= 'Emirati Arabi Uniti';
UPDATE STATI SET Capitale = 'Asmara' WHERE DESCRIZIONE= 'Eritrea';
UPDATE STATI SET Capitale = 'Tallinn' WHERE DESCRIZIONE= 'Estonia';
UPDATE STATI SET Capitale = 'Addis Abeba' WHERE DESCRIZIONE= 'Etiopia';
UPDATE STATI SET Capitale = 'Suva' WHERE DESCRIZIONE= 'Figi';
UPDATE STATI SET Capitale = 'Manila' WHERE DESCRIZIONE= 'Filippine';
UPDATE STATI SET Capitale = 'Helsinki' WHERE DESCRIZIONE= 'Finlandia';
UPDATE STATI SET Capitale = 'Parigi' WHERE DESCRIZIONE= 'Francia';
UPDATE STATI SET Capitale = 'Libreville' WHERE DESCRIZIONE= 'Gabon';
UPDATE STATI SET Capitale = 'Banjul' WHERE DESCRIZIONE= 'Gambia';
UPDATE STATI SET Capitale = 'Tbilisi' WHERE DESCRIZIONE= 'Georgia';
UPDATE STATI SET Capitale = 'Berlino' WHERE DESCRIZIONE= 'Germania';
UPDATE STATI SET Capitale = 'Accra' WHERE DESCRIZIONE= 'Ghana';
UPDATE STATI SET Capitale = 'Kingston' WHERE DESCRIZIONE= 'Giamaica';
UPDATE STATI SET Capitale = 'Tokyo' WHERE DESCRIZIONE= 'Giappone';
UPDATE STATI SET Capitale = 'Gibuti' WHERE DESCRIZIONE= 'Gibuti';
UPDATE STATI SET Capitale = 'Amman' WHERE DESCRIZIONE= 'Giordania';
UPDATE STATI SET Capitale = 'Atene' WHERE DESCRIZIONE= 'Grecia';
UPDATE STATI SET Capitale = 'Saint George''s' WHERE DESCRIZIONE= 'Grenada';
UPDATE STATI SET Capitale = 'Città del Guatemala' WHERE DESCRIZIONE= 'Guatemala';
UPDATE STATI SET Capitale = 'Conakry' WHERE DESCRIZIONE= 'Guinea';
UPDATE STATI SET Capitale = 'Bissau' WHERE DESCRIZIONE= 'Guinea-Bissau';
UPDATE STATI SET Capitale = 'Malabo' WHERE DESCRIZIONE= 'Guinea Equatoriale';
UPDATE STATI SET Capitale = 'Georgetown' WHERE DESCRIZIONE= 'Guyana';
UPDATE STATI SET Capitale = 'Port-au-Prince' WHERE DESCRIZIONE= 'Haiti';
UPDATE STATI SET Capitale = 'Tegucigalpa' WHERE DESCRIZIONE= 'Honduras';
UPDATE STATI SET Capitale = 'Nuova Delhi' WHERE DESCRIZIONE= 'India';
UPDATE STATI SET Capitale = 'Giacarta' WHERE DESCRIZIONE= 'Indonesia';
UPDATE STATI SET Capitale = 'Teheran' WHERE DESCRIZIONE= 'Iran';
UPDATE STATI SET Capitale = 'Baghdad' WHERE DESCRIZIONE= 'Iraq';
UPDATE STATI SET Capitale = 'Dublino' WHERE DESCRIZIONE= 'Irlanda';
UPDATE STATI SET Capitale = 'Reykjavìk' WHERE DESCRIZIONE= 'Islanda';
UPDATE STATI SET Capitale = 'Majuro' WHERE DESCRIZIONE= 'Isole Marshall';
UPDATE STATI SET Capitale = 'Honiara' WHERE DESCRIZIONE= 'Isole Salomone';
UPDATE STATI SET Capitale = 'Gerusalemme' WHERE DESCRIZIONE= 'Israele';
UPDATE STATI SET Capitale = 'Roma' WHERE DESCRIZIONE= 'Italia';
UPDATE STATI SET Capitale = 'Nur-Sultan' WHERE DESCRIZIONE= 'Kazakistan';
UPDATE STATI SET Capitale = 'Nairobi' WHERE DESCRIZIONE= 'Kenya';
UPDATE STATI SET Capitale = 'Bishkek' WHERE DESCRIZIONE= 'Kirghizistan';
UPDATE STATI SET Capitale = 'Bairiki' WHERE DESCRIZIONE= 'Kiribati';
UPDATE STATI SET Capitale = 'Madinat al-Kuwait' WHERE DESCRIZIONE= 'Kuwait';
UPDATE STATI SET Capitale = 'Vientiane' WHERE DESCRIZIONE= 'Laos';
UPDATE STATI SET Capitale = 'Maseru' WHERE DESCRIZIONE= 'Lesotho';
UPDATE STATI SET Capitale = 'Riga' WHERE DESCRIZIONE= 'Lettonia';
UPDATE STATI SET Capitale = 'Beirut' WHERE DESCRIZIONE= 'Libano';
UPDATE STATI SET Capitale = 'Monrovia' WHERE DESCRIZIONE= 'Liberia';
UPDATE STATI SET Capitale = 'Tripoli' WHERE DESCRIZIONE= 'Libia';
UPDATE STATI SET Capitale = 'Vaduz' WHERE DESCRIZIONE= 'Liechtenstein';
UPDATE STATI SET Capitale = 'Vilnius' WHERE DESCRIZIONE= 'Lituania';
UPDATE STATI SET Capitale = 'Lussemburgo' WHERE DESCRIZIONE= 'Lussemburgo';
UPDATE STATI SET Capitale = 'Skopje' WHERE DESCRIZIONE= 'Macedonia del Nord';
UPDATE STATI SET Capitale = 'Antananarivo' WHERE DESCRIZIONE= 'Madagascar';
UPDATE STATI SET Capitale = 'Lilongwe' WHERE DESCRIZIONE= 'Malawi';
UPDATE STATI SET Capitale = 'Malé' WHERE DESCRIZIONE= 'Maldive';
UPDATE STATI SET Capitale = 'Kuala Lumpur' WHERE DESCRIZIONE= 'Malesia';
UPDATE STATI SET Capitale = 'Bamako' WHERE DESCRIZIONE= 'Mali';
UPDATE STATI SET Capitale = 'La Valletta' WHERE DESCRIZIONE= 'Malta';
UPDATE STATI SET Capitale = 'Rabat' WHERE DESCRIZIONE= 'Marocco';
UPDATE STATI SET Capitale = 'Nouakchott' WHERE DESCRIZIONE= 'Mauritania';
UPDATE STATI SET Capitale = 'Port Louis' WHERE DESCRIZIONE= 'Mauritius';
UPDATE STATI SET Capitale = 'Città del Messico' WHERE DESCRIZIONE= 'Messico';
UPDATE STATI SET Capitale = 'Palikir' WHERE DESCRIZIONE= 'Micronesia';
UPDATE STATI SET Capitale = 'Chișinău' WHERE DESCRIZIONE= 'Moldavia';
UPDATE STATI SET Capitale = 'Monaco (città-DESCRIZIONE)' WHERE DESCRIZIONE= 'Monaco';
UPDATE STATI SET Capitale = 'Ulan Bator' WHERE DESCRIZIONE= 'Mongolia';
UPDATE STATI SET Capitale = 'Podgorica' WHERE DESCRIZIONE= 'Montenegro';
UPDATE STATI SET Capitale = 'Maputo' WHERE DESCRIZIONE= 'Mozambico';
UPDATE STATI SET Capitale = 'Windhoek' WHERE DESCRIZIONE= 'Namibia';
UPDATE STATI SET Capitale = 'Nessuna - Yaren (de facto)' WHERE DESCRIZIONE= 'Nauru';
UPDATE STATI SET Capitale = 'Kathmandu' WHERE DESCRIZIONE= 'Nepal';
UPDATE STATI SET Capitale = 'Managua' WHERE DESCRIZIONE= 'Nicaragua';
UPDATE STATI SET Capitale = 'Niamey' WHERE DESCRIZIONE= 'Niger';
UPDATE STATI SET Capitale = 'Abuja' WHERE DESCRIZIONE= 'Nigeria';
UPDATE STATI SET Capitale = 'Oslo' WHERE DESCRIZIONE= 'Norvegia';
UPDATE STATI SET Capitale = 'Wellington' WHERE DESCRIZIONE= 'Nuova Zelanda';
UPDATE STATI SET Capitale = 'Mascate' WHERE DESCRIZIONE= 'Oman';
UPDATE STATI SET Capitale = 'Amsterdam' WHERE DESCRIZIONE= 'Paesi Bassi';
UPDATE STATI SET Capitale = 'Islamabad' WHERE DESCRIZIONE= 'Pakistan';
UPDATE STATI SET Capitale = 'Ngerulmud' WHERE DESCRIZIONE= 'Palau';
UPDATE STATI SET Capitale = 'Gerusalemme Est (proclamata) - Ramallah (de facto)' WHERE DESCRIZIONE= 'Palestina';
UPDATE STATI SET Capitale = 'Panama' WHERE DESCRIZIONE= 'Panama';
UPDATE STATI SET Capitale = 'Port Moresby' WHERE DESCRIZIONE= 'Papua Nuova Guinea';
UPDATE STATI SET Capitale = 'Asunciòn' WHERE DESCRIZIONE= 'Paraguay';
UPDATE STATI SET Capitale = 'Lima' WHERE DESCRIZIONE= 'Perù';
UPDATE STATI SET Capitale = 'Varsavia' WHERE DESCRIZIONE= 'Polonia';
UPDATE STATI SET Capitale = 'Lisbona' WHERE DESCRIZIONE= 'Portogallo';
UPDATE STATI SET Capitale = 'Doha' WHERE DESCRIZIONE= 'Qatar';
UPDATE STATI SET Capitale = 'Londra' WHERE DESCRIZIONE= 'Regno Unito';
UPDATE STATI SET Capitale = 'Praga' WHERE DESCRIZIONE= 'Repubblica Ceca';
UPDATE STATI SET Capitale = 'Bangui' WHERE DESCRIZIONE= 'Repubblica Centrafricana';
UPDATE STATI SET Capitale = 'Santo Domingo' WHERE DESCRIZIONE= 'Repubblica Dominicana';
UPDATE STATI SET Capitale = 'Bucarest' WHERE DESCRIZIONE= 'Romania';
UPDATE STATI SET Capitale = 'Kigali' WHERE DESCRIZIONE= 'Ruanda';
UPDATE STATI SET Capitale = 'Mosca' WHERE DESCRIZIONE= 'Russia';
UPDATE STATI SET Capitale = 'Basseterre' WHERE DESCRIZIONE= 'Saint Kitts e Nevis';
UPDATE STATI SET Capitale = 'Kingstown' WHERE DESCRIZIONE= 'Saint Vincent e Grenadine';
UPDATE STATI SET Capitale = 'Apia' WHERE DESCRIZIONE= 'Samoa';
UPDATE STATI SET Capitale = 'Città di San Marino' WHERE DESCRIZIONE= 'San Marino';
UPDATE STATI SET Capitale = 'Castries' WHERE DESCRIZIONE= 'Santa Lucia';
UPDATE STATI SET Capitale = 'Sao Tomé' WHERE DESCRIZIONE= 'Sao Tomé e Prìncipe';
UPDATE STATI SET Capitale = 'Dakar' WHERE DESCRIZIONE= 'Senegal';
UPDATE STATI SET Capitale = 'Belgrado' WHERE DESCRIZIONE= 'Serbia';
UPDATE STATI SET Capitale = 'Victoria' WHERE DESCRIZIONE= 'Seychelles';
UPDATE STATI SET Capitale = 'Freetown' WHERE DESCRIZIONE= 'Sierra Leone';
UPDATE STATI SET Capitale = 'Singapore (città-DESCRIZIONE)' WHERE DESCRIZIONE= 'Singapore';
UPDATE STATI SET Capitale = 'Damasco' WHERE DESCRIZIONE= 'Siria';
UPDATE STATI SET Capitale = 'Bratislava' WHERE DESCRIZIONE= 'Slovacchia';
UPDATE STATI SET Capitale = 'Lubiana' WHERE DESCRIZIONE= 'Slovenia';
UPDATE STATI SET Capitale = 'Mogadiscio' WHERE DESCRIZIONE= 'Somalia';
UPDATE STATI SET Capitale = 'Madrid' WHERE DESCRIZIONE= 'Spagna';
UPDATE STATI SET Capitale = 'Sri Jayawardenapura Kotte' WHERE DESCRIZIONE= 'Sri Lanka';
UPDATE STATI SET Capitale = 'Washington' WHERE DESCRIZIONE= 'Stati Uniti';
UPDATE STATI SET Capitale = 'Pretoria (amministrativa) - Città del Capo (legislativa) - Bloemfontein (giudiziaria)' WHERE DESCRIZIONE= 'Sudafrica';
UPDATE STATI SET Capitale = 'Khartum' WHERE DESCRIZIONE= 'Sudan';
UPDATE STATI SET Capitale = 'Juba' WHERE DESCRIZIONE= 'Sudan del Sud';
UPDATE STATI SET Capitale = 'Paramaribo' WHERE DESCRIZIONE= 'Suriname';
UPDATE STATI SET Capitale = 'Stoccolma' WHERE DESCRIZIONE= 'Svezia';
UPDATE STATI SET Capitale = 'Berna' WHERE DESCRIZIONE= 'Svizzera';
UPDATE STATI SET Capitale = 'Mbabane (amministrativa e giudiziaria) - Lobamba (legislativa)' WHERE DESCRIZIONE= 'Swaziland';
UPDATE STATI SET Capitale = 'Dušanbe' WHERE DESCRIZIONE= 'Tagikistan';
UPDATE STATI SET Capitale = 'Taipei' WHERE DESCRIZIONE= 'Taiwan';
UPDATE STATI SET Capitale = 'Dodoma' WHERE DESCRIZIONE= 'Tanzania';
UPDATE STATI SET Capitale = 'Bangkok' WHERE DESCRIZIONE= 'Thailandia';
UPDATE STATI SET Capitale = 'Dili' WHERE DESCRIZIONE= 'Timor Est';
UPDATE STATI SET Capitale = 'Lomé' WHERE DESCRIZIONE= 'Togo';
UPDATE STATI SET Capitale = 'Nukuʻalofa' WHERE DESCRIZIONE= 'Tonga';
UPDATE STATI SET Capitale = 'Port of Spain' WHERE DESCRIZIONE= 'Trinidad e Tobago';
UPDATE STATI SET Capitale = 'Tunisi' WHERE DESCRIZIONE= 'Tunisia';
UPDATE STATI SET Capitale = 'Ankara' WHERE DESCRIZIONE= 'Turchia';
UPDATE STATI SET Capitale = 'Ashgabat' WHERE DESCRIZIONE= 'Turkmenistan';
UPDATE STATI SET Capitale = 'Funafuti' WHERE DESCRIZIONE= 'Tuvalu';
UPDATE STATI SET Capitale = 'Kiev' WHERE DESCRIZIONE= 'Ucraina';
UPDATE STATI SET Capitale = 'Kampala' WHERE DESCRIZIONE= 'Uganda';
UPDATE STATI SET Capitale = 'Budapest' WHERE DESCRIZIONE= 'Ungheria';
UPDATE STATI SET Capitale = 'Montevideo' WHERE DESCRIZIONE= 'Uruguay';
UPDATE STATI SET Capitale = 'Tashkent' WHERE DESCRIZIONE= 'Uzbekistan';
UPDATE STATI SET Capitale = 'Port Vila' WHERE DESCRIZIONE= 'Vanuatu';
UPDATE STATI SET Capitale = 'Caracas' WHERE DESCRIZIONE= 'Venezuela';
UPDATE STATI SET Capitale = 'Hanoi' WHERE DESCRIZIONE= 'Vietnam';
UPDATE STATI SET Capitale = 'San''a' WHERE DESCRIZIONE= 'Yemen';
UPDATE STATI SET Capitale = 'Lusaka' WHERE DESCRIZIONE= 'Zambia';
UPDATE STATI SET Capitale = 'Harare' WHERE DESCRIZIONE= 'Zimbabwe';