ALTER TABLE STATI ADD
    Descrizione VARCHAR(40);

UPDATE STATI SET Descrizione = 'Afghanistan' WHERE STATO= 'AFG';
UPDATE STATI SET Descrizione = 'Albania' WHERE STATO= 'ALB';
UPDATE STATI SET Descrizione = 'Algeria' WHERE STATO= 'DZA';
UPDATE STATI SET Descrizione = 'Andorra' WHERE STATO= 'AND';
UPDATE STATI SET Descrizione = 'Angola' WHERE STATO= 'AGO';
UPDATE STATI SET Descrizione = 'Anguilla' WHERE STATO= 'AIA';
UPDATE STATI SET Descrizione = 'Antartide' WHERE STATO= 'ATA';
UPDATE STATI SET Descrizione = 'Antigua e Barbuda' WHERE STATO= 'ATG';
UPDATE STATI SET Descrizione = 'Antille Olandesi' WHERE STATO= 'ANT';
UPDATE STATI SET Descrizione = 'Arabia Saudita' WHERE STATO= 'SAU';
UPDATE STATI SET Descrizione = 'Argentina' WHERE STATO= 'ARG';
UPDATE STATI SET Descrizione = 'Armenia' WHERE STATO= 'ARM';
UPDATE STATI SET Descrizione = 'Aruba' WHERE STATO= 'ABW';
UPDATE STATI SET Descrizione = 'Australia' WHERE STATO= 'AUS';
UPDATE STATI SET Descrizione = 'Austria' WHERE STATO= 'AUT';
UPDATE STATI SET Descrizione = 'Azerbaijan' WHERE STATO= 'AZE';
UPDATE STATI SET Descrizione = 'Bahamas' WHERE STATO= 'BHS';
UPDATE STATI SET Descrizione = 'Bahrain' WHERE STATO= 'BHR';
UPDATE STATI SET Descrizione = 'Bangladesh' WHERE STATO= 'BGD';
UPDATE STATI SET Descrizione = 'Barbados' WHERE STATO= 'BRB';
UPDATE STATI SET Descrizione = 'Belgio' WHERE STATO= 'BEL';
UPDATE STATI SET Descrizione = 'Belize' WHERE STATO= 'BLZ';
UPDATE STATI SET Descrizione = 'Benin' WHERE STATO= 'BEN';
UPDATE STATI SET Descrizione = 'Bermuda' WHERE STATO= 'BMU';
UPDATE STATI SET Descrizione = 'Bielorussia' WHERE STATO= 'BLR';
UPDATE STATI SET Descrizione = 'Bhutan' WHERE STATO= 'BTN';
UPDATE STATI SET Descrizione = 'Bolivia' WHERE STATO= 'BOL';
UPDATE STATI SET Descrizione = 'Bosnia Erzegovina' WHERE STATO= 'BIH';
UPDATE STATI SET Descrizione = 'Botswana' WHERE STATO= 'BWA';
UPDATE STATI SET Descrizione = 'Brasile' WHERE STATO= 'BRA';
UPDATE STATI SET Descrizione = 'Brunei Darussalam' WHERE STATO= 'BRN';
UPDATE STATI SET Descrizione = 'Bulgaria' WHERE STATO= 'BGR';
UPDATE STATI SET Descrizione = 'Burkina Faso' WHERE STATO= 'BFA';
UPDATE STATI SET Descrizione = 'Burundi' WHERE STATO= 'BDI';
UPDATE STATI SET Descrizione = 'Cambogia' WHERE STATO= 'KHM';
UPDATE STATI SET Descrizione = 'Camerun' WHERE STATO= 'CMR';
UPDATE STATI SET Descrizione = 'Canada' WHERE STATO= 'CAN';
UPDATE STATI SET Descrizione = 'Capo Verde' WHERE STATO= 'CPV';
UPDATE STATI SET Descrizione = 'Ciad' WHERE STATO= 'TCD';
UPDATE STATI SET Descrizione = 'Cile' WHERE STATO= 'CHL';
UPDATE STATI SET Descrizione = 'Cina' WHERE STATO= 'CHN';
UPDATE STATI SET Descrizione = 'Cipro' WHERE STATO= 'CYP';
UPDATE STATI SET Descrizione = 'Citta del Vaticano' WHERE STATO= 'VAT';
UPDATE STATI SET Descrizione = 'Colombia' WHERE STATO= 'COL';
UPDATE STATI SET Descrizione = 'Comore' WHERE STATO= 'COM';
UPDATE STATI SET Descrizione = 'Corea del Nord' WHERE STATO= 'PRK';
UPDATE STATI SET Descrizione = 'Corea del Sud' WHERE STATO= 'KOR';
UPDATE STATI SET Descrizione = 'Costa Rica' WHERE STATO= 'CRI';
UPDATE STATI SET Descrizione = 'Costa d''Avorio' WHERE STATO= 'CIV';
UPDATE STATI SET Descrizione = 'Croazia' WHERE STATO= 'HRV';
UPDATE STATI SET Descrizione = 'Cuba' WHERE STATO= 'CUB';
UPDATE STATI SET Descrizione = 'Danimarca' WHERE STATO= 'DNK';
UPDATE STATI SET Descrizione = 'Dominica' WHERE STATO= 'DMA';
UPDATE STATI SET Descrizione = 'Ecuador' WHERE STATO= 'ECU';
UPDATE STATI SET Descrizione = 'Egitto' WHERE STATO= 'EGY';
UPDATE STATI SET Descrizione = 'Eire' WHERE STATO= 'IRL';
UPDATE STATI SET Descrizione = 'El Salvador' WHERE STATO= 'SLV';
UPDATE STATI SET Descrizione = 'Emirati Arabi Uniti' WHERE STATO= 'ARE';
UPDATE STATI SET Descrizione = 'Eritrea' WHERE STATO= 'ERI';
UPDATE STATI SET Descrizione = 'Estonia' WHERE STATO= 'EST';
UPDATE STATI SET Descrizione = 'Etiopia' WHERE STATO= 'ETH';
UPDATE STATI SET Descrizione = 'Federazione Russa' WHERE STATO= 'RUS';
UPDATE STATI SET Descrizione = 'Fiji' WHERE STATO= 'FJI';
UPDATE STATI SET Descrizione = 'Filippine' WHERE STATO= 'PHL';
UPDATE STATI SET Descrizione = 'Finlandia' WHERE STATO= 'FIN';
UPDATE STATI SET Descrizione = 'Francia' WHERE STATO= 'FRA';
UPDATE STATI SET Descrizione = 'Gabon' WHERE STATO= 'GAB';
UPDATE STATI SET Descrizione = 'Gambia' WHERE STATO= 'GMB';
UPDATE STATI SET Descrizione = 'Georgia' WHERE STATO= 'GEO';
UPDATE STATI SET Descrizione = 'Germania' WHERE STATO= 'DEU';
UPDATE STATI SET Descrizione = 'Ghana' WHERE STATO= 'GHA';
UPDATE STATI SET Descrizione = 'Giamaica' WHERE STATO= 'JAM';
UPDATE STATI SET Descrizione = 'Giappone' WHERE STATO= 'JPN';
UPDATE STATI SET Descrizione = 'Gibilterra' WHERE STATO= 'GIB';
UPDATE STATI SET Descrizione = 'Gibuti' WHERE STATO= 'DJI';
UPDATE STATI SET Descrizione = 'Giordania' WHERE STATO= 'JOR';
UPDATE STATI SET Descrizione = 'Grecia' WHERE STATO= 'GRC';
UPDATE STATI SET Descrizione = 'Grenada' WHERE STATO= 'GRD';
UPDATE STATI SET Descrizione = 'Groenlandia' WHERE STATO= 'GRL';
UPDATE STATI SET Descrizione = 'Guadalupa' WHERE STATO= 'GLP';
UPDATE STATI SET Descrizione = 'Guam' WHERE STATO= 'GUM';
UPDATE STATI SET Descrizione = 'Guatemala' WHERE STATO= 'GTM';
UPDATE STATI SET Descrizione = 'Guinea' WHERE STATO= 'GIN';
UPDATE STATI SET Descrizione = 'Guinea-Bissau' WHERE STATO= 'GNB';
UPDATE STATI SET Descrizione = 'Guinea Equatoriale' WHERE STATO= 'GNQ';
UPDATE STATI SET Descrizione = 'Guyana' WHERE STATO= 'GUY';
UPDATE STATI SET Descrizione = 'Guyana Francese' WHERE STATO= 'GUF';
UPDATE STATI SET Descrizione = 'Haiti' WHERE STATO= 'HTI';
UPDATE STATI SET Descrizione = 'Honduras' WHERE STATO= 'HND';
UPDATE STATI SET Descrizione = 'Hong Kong' WHERE STATO= 'HKG';
UPDATE STATI SET Descrizione = 'India' WHERE STATO= 'IND';
UPDATE STATI SET Descrizione = 'Indonesia' WHERE STATO= 'IDN';
UPDATE STATI SET Descrizione = 'Iran' WHERE STATO= 'IRN';
UPDATE STATI SET Descrizione = 'Iraq' WHERE STATO= 'IRQ';
UPDATE STATI SET Descrizione = 'Isola di Bouvet' WHERE STATO= 'BVT';
UPDATE STATI SET Descrizione = 'Isola di Natale' WHERE STATO= 'CXR';
UPDATE STATI SET Descrizione = 'Isola Heard e Isole McDonald' WHERE STATO= 'HMD';
UPDATE STATI SET Descrizione = 'Isole Cayman' WHERE STATO= 'CYM';
UPDATE STATI SET Descrizione = 'Isole Cocos' WHERE STATO= 'CCK';
UPDATE STATI SET Descrizione = 'Isole Cook' WHERE STATO= 'COK';
UPDATE STATI SET Descrizione = 'Isole Falkland' WHERE STATO= 'FLK';
UPDATE STATI SET Descrizione = 'Isole Faroe' WHERE STATO= 'FRO';
UPDATE STATI SET Descrizione = 'Isole Marshall' WHERE STATO= 'MHL';
UPDATE STATI SET Descrizione = 'Isole Marianne Settentrionali' WHERE STATO= 'MNP';
UPDATE STATI SET Descrizione = 'Isole Minori degli Stati Uniti d''America' WHERE STATO= 'UMI';
UPDATE STATI SET Descrizione = 'Isola Norfolk' WHERE STATO= 'NFK';
UPDATE STATI SET Descrizione = 'Isole Solomon' WHERE STATO= 'SLB';
UPDATE STATI SET Descrizione = 'Isole Turks e Caicos' WHERE STATO= 'TCA';
UPDATE STATI SET Descrizione = 'Isole Vergini Americane' WHERE STATO= 'VIR';
UPDATE STATI SET Descrizione = 'Isole Vergini Britanniche' WHERE STATO= 'VGB';
UPDATE STATI SET Descrizione = 'Israele' WHERE STATO= 'ISR';
UPDATE STATI SET Descrizione = 'Islanda' WHERE STATO= 'ISL';
UPDATE STATI SET Descrizione = 'Italia' WHERE STATO= 'ITA';
UPDATE STATI SET Descrizione = 'Kazakhistan' WHERE STATO= 'KAZ';
UPDATE STATI SET Descrizione = 'Kenya' WHERE STATO= 'KEN';
UPDATE STATI SET Descrizione = 'Kirghizistan' WHERE STATO= 'KGZ';
UPDATE STATI SET Descrizione = 'Kiribati' WHERE STATO= 'KIR';
UPDATE STATI SET Descrizione = 'Kuwait' WHERE STATO= 'KWT';
UPDATE STATI SET Descrizione = 'Laos' WHERE STATO= 'LAO';
UPDATE STATI SET Descrizione = 'Lettonia' WHERE STATO= 'LVA';
UPDATE STATI SET Descrizione = 'Lesotho' WHERE STATO= 'LSO';
UPDATE STATI SET Descrizione = 'Libano' WHERE STATO= 'LBN';
UPDATE STATI SET Descrizione = 'Liberia' WHERE STATO= 'LBR';
UPDATE STATI SET Descrizione = 'Libia' WHERE STATO= 'LBY';
UPDATE STATI SET Descrizione = 'Liechtenstein' WHERE STATO= 'LIE';
UPDATE STATI SET Descrizione = 'Lituania' WHERE STATO= 'LTU';
UPDATE STATI SET Descrizione = 'Lussemburgo' WHERE STATO= 'LUX';
UPDATE STATI SET Descrizione = 'Macao' WHERE STATO= 'MAC';
UPDATE STATI SET Descrizione = 'Macedonia' WHERE STATO= 'MKD';
UPDATE STATI SET Descrizione = 'Madagascar' WHERE STATO= 'MDG';
UPDATE STATI SET Descrizione = 'Malawi' WHERE STATO= 'MWI';
UPDATE STATI SET Descrizione = 'Maldive' WHERE STATO= 'MDV';
UPDATE STATI SET Descrizione = 'Malesia' WHERE STATO= 'MYS';
UPDATE STATI SET Descrizione = 'Mali' WHERE STATO= 'MLI';
UPDATE STATI SET Descrizione = 'Malta' WHERE STATO= 'MLT';
UPDATE STATI SET Descrizione = 'Marocco' WHERE STATO= 'MAR';
UPDATE STATI SET Descrizione = 'Martinica' WHERE STATO= 'MTQ';
UPDATE STATI SET Descrizione = 'Mauritania' WHERE STATO= 'MRT';
UPDATE STATI SET Descrizione = 'Maurizius' WHERE STATO= 'MUS';
UPDATE STATI SET Descrizione = 'Mayotte' WHERE STATO= 'MYT';
UPDATE STATI SET Descrizione = 'Messico' WHERE STATO= 'MEX';
UPDATE STATI SET Descrizione = 'Moldavia' WHERE STATO= 'MDA';
UPDATE STATI SET Descrizione = 'Monaco' WHERE STATO= 'MCO';
UPDATE STATI SET Descrizione = 'Mongolia' WHERE STATO= 'MNG';
UPDATE STATI SET Descrizione = 'Montserrat' WHERE STATO= 'MSR';
UPDATE STATI SET Descrizione = 'Mozambico' WHERE STATO= 'MOZ';
UPDATE STATI SET Descrizione = 'Myanmar' WHERE STATO= 'MMR';
UPDATE STATI SET Descrizione = 'Namibia' WHERE STATO= 'NAM';
UPDATE STATI SET Descrizione = 'Nauru' WHERE STATO= 'NRU';
UPDATE STATI SET Descrizione = 'Nepal' WHERE STATO= 'NPL';
UPDATE STATI SET Descrizione = 'Nicaragua' WHERE STATO= 'NIC';
UPDATE STATI SET Descrizione = 'Niger' WHERE STATO= 'NER';
UPDATE STATI SET Descrizione = 'Nigeria' WHERE STATO= 'NGA';
UPDATE STATI SET Descrizione = 'Niue' WHERE STATO= 'NIU';
UPDATE STATI SET Descrizione = 'Norvegia' WHERE STATO= 'NOR';
UPDATE STATI SET Descrizione = 'Nuova Caledonia' WHERE STATO= 'NCL';
UPDATE STATI SET Descrizione = 'Nuova Zelanda' WHERE STATO= 'NZL';
UPDATE STATI SET Descrizione = 'Oman' WHERE STATO= 'OMN';
UPDATE STATI SET Descrizione = 'Paesi Bassi' WHERE STATO= 'NLD';
UPDATE STATI SET Descrizione = 'Pakistan' WHERE STATO= 'PAK';
UPDATE STATI SET Descrizione = 'Palau' WHERE STATO= 'PLW';
UPDATE STATI SET Descrizione = 'Panama' WHERE STATO= 'PAN';
UPDATE STATI SET Descrizione = 'Papua Nuova Guinea' WHERE STATO= 'PNG';
UPDATE STATI SET Descrizione = 'Paraguay' WHERE STATO= 'PRY';
UPDATE STATI SET Descrizione = 'Peru' WHERE STATO= 'PER';
UPDATE STATI SET Descrizione = 'Pitcairn' WHERE STATO= 'PCN';
UPDATE STATI SET Descrizione = 'Polinesia Francese' WHERE STATO= 'PYF';
UPDATE STATI SET Descrizione = 'Polonia' WHERE STATO= 'POL';
UPDATE STATI SET Descrizione = 'Portogallo' WHERE STATO= 'PRT';
UPDATE STATI SET Descrizione = 'Porto Rico' WHERE STATO= 'PRI';
UPDATE STATI SET Descrizione = 'Qatar' WHERE STATO= 'QAT';
UPDATE STATI SET Descrizione = 'Regno Unito' WHERE STATO= 'GBR';
UPDATE STATI SET Descrizione = 'Repubblica Ceca' WHERE STATO= 'CZE';
UPDATE STATI SET Descrizione = 'Repubblica Centroafricana' WHERE STATO= 'CAF';
UPDATE STATI SET Descrizione = 'Repubblica del Congo' WHERE STATO= 'COG';
UPDATE STATI SET Descrizione = 'Repubblica Democratica del Congo' WHERE STATO= 'COD';
UPDATE STATI SET Descrizione = 'Repubblica Dominicana' WHERE STATO= 'DOM';
UPDATE STATI SET Descrizione = 'Reunion' WHERE STATO= 'REU';
UPDATE STATI SET Descrizione = 'Romania' WHERE STATO= 'ROU';
UPDATE STATI SET Descrizione = 'Ruanda' WHERE STATO= 'RWA';
UPDATE STATI SET Descrizione = 'Sahara Occidentale' WHERE STATO= 'ESH';
UPDATE STATI SET Descrizione = 'Saint Kitts e Nevis' WHERE STATO= 'KNA';
UPDATE STATI SET Descrizione = 'Saint Pierre e Miquelon' WHERE STATO= 'SPM';
UPDATE STATI SET Descrizione = 'Saint Vincent e Grenadine' WHERE STATO= 'VCT';
UPDATE STATI SET Descrizione = 'Samoa' WHERE STATO= 'WSM';
UPDATE STATI SET Descrizione = 'Samoa Americane' WHERE STATO= 'ASM';
UPDATE STATI SET Descrizione = 'San Marino' WHERE STATO= 'SMR';
UPDATE STATI SET Descrizione = 'Sant''Elena' WHERE STATO= 'SHN';
UPDATE STATI SET Descrizione = 'Santa Lucia' WHERE STATO= 'LCA';
UPDATE STATI SET Descrizione = 'Sao Tome e Principe' WHERE STATO= 'STP';
UPDATE STATI SET Descrizione = 'Senegal' WHERE STATO= 'SEN';
UPDATE STATI SET Descrizione = 'Kosovo' WHERE STATO= 'XXK';
UPDATE STATI SET Descrizione = 'Seychelles' WHERE STATO= 'SYC';
UPDATE STATI SET Descrizione = 'Sierra Leone' WHERE STATO= 'SLE';
UPDATE STATI SET Descrizione = 'Singapore' WHERE STATO= 'SGP';
UPDATE STATI SET Descrizione = 'Siria' WHERE STATO= 'SYR';
UPDATE STATI SET Descrizione = 'Slovacchia' WHERE STATO= 'SVK';
UPDATE STATI SET Descrizione = 'Slovenia' WHERE STATO= 'SVN';
UPDATE STATI SET Descrizione = 'Somalia' WHERE STATO= 'SOM';
UPDATE STATI SET Descrizione = 'Spagna' WHERE STATO= 'ESP';
UPDATE STATI SET Descrizione = 'Sri Lanka' WHERE STATO= 'LKA';
UPDATE STATI SET Descrizione = 'Stati Federati della Micronesia' WHERE STATO= 'FSM';
UPDATE STATI SET Descrizione = 'Stati Uniti d''America' WHERE STATO= 'USA';
UPDATE STATI SET Descrizione = 'Sud Africa' WHERE STATO= 'ZAF';
UPDATE STATI SET Descrizione = 'Sud Georgia e Isole Sandwich' WHERE STATO= 'SGS';
UPDATE STATI SET Descrizione = 'Sudan' WHERE STATO= 'SDN';
UPDATE STATI SET Descrizione = 'Suriname' WHERE STATO= 'SUR';
UPDATE STATI SET Descrizione = 'Svalbard e Jan Mayen' WHERE STATO= 'SJM';
UPDATE STATI SET Descrizione = 'Svezia' WHERE STATO= 'SWE';
UPDATE STATI SET Descrizione = 'Svizzera' WHERE STATO= 'CHE';
UPDATE STATI SET Descrizione = 'Swaziland' WHERE STATO= 'SWZ';
UPDATE STATI SET Descrizione = 'Tagikistan' WHERE STATO= 'TJK';
UPDATE STATI SET Descrizione = 'Tailandia' WHERE STATO= 'THA';
UPDATE STATI SET Descrizione = 'Taiwan' WHERE STATO= 'TWN';
UPDATE STATI SET Descrizione = 'Tanzania' WHERE STATO= 'TZA';
UPDATE STATI SET Descrizione = 'Territori Britannici dell''Oceano Indiano' WHERE STATO= 'IOT';
UPDATE STATI SET Descrizione = 'Territori Francesi del Sud' WHERE STATO= 'ATF';
UPDATE STATI SET Descrizione = 'Territori Palestinesi Occupati' WHERE STATO= 'PSE';
UPDATE STATI SET Descrizione = 'Timor Est' WHERE STATO= 'TLS';
UPDATE STATI SET Descrizione = 'Togo' WHERE STATO= 'TGO';
UPDATE STATI SET Descrizione = 'Tokelau' WHERE STATO= 'TKL';
UPDATE STATI SET Descrizione = 'Tonga' WHERE STATO= 'TON';
UPDATE STATI SET Descrizione = 'Trinidad e Tobago' WHERE STATO= 'TTO';
UPDATE STATI SET Descrizione = 'Tunisia' WHERE STATO= 'TUN';
UPDATE STATI SET Descrizione = 'Turchia' WHERE STATO= 'TUR';
UPDATE STATI SET Descrizione = 'Turkmenistan' WHERE STATO= 'TKM';
UPDATE STATI SET Descrizione = 'Tuvalu' WHERE STATO= 'TUV';
UPDATE STATI SET Descrizione = 'Ucraina' WHERE STATO= 'UKR';
UPDATE STATI SET Descrizione = 'Uganda' WHERE STATO= 'UGA';
UPDATE STATI SET Descrizione = 'Ungheria' WHERE STATO= 'HUN';
UPDATE STATI SET Descrizione = 'Uruguay' WHERE STATO= 'URY';
UPDATE STATI SET Descrizione = 'Uzbekistan' WHERE STATO= 'UZB';
UPDATE STATI SET Descrizione = 'Vanuatu' WHERE STATO= 'VUT';
UPDATE STATI SET Descrizione = 'Venezuela' WHERE STATO= 'VEN';
UPDATE STATI SET Descrizione = 'Vietnam' WHERE STATO= 'VNM';
UPDATE STATI SET Descrizione = 'Wallis e Futuna' WHERE STATO= 'WLF';
UPDATE STATI SET Descrizione = 'Yemen' WHERE STATO= 'YEM';
UPDATE STATI SET Descrizione = 'Zambia' WHERE STATO= 'ZMB';
UPDATE STATI SET Descrizione = 'Zimbabwe' WHERE STATO= 'ZWE';
UPDATE STATI SET Descrizione = 'Serbia' WHERE STATO= 'SRB';
UPDATE STATI SET Descrizione = 'Montenegro' WHERE STATO= 'MNE';
UPDATE STATI SET Descrizione = 'Timor Est' WHERE STATO= 'TLS';
UPDATE STATI SET Descrizione = 'Guernsey' WHERE STATO= 'GGY';