--UNIVERSITA' DEGLI STUDI DI NAPOLI FEDERICO II
--FACOLTA' DI INGEGNERIA INFORMATICA
--ANNO ACCADEMICO 2019/20
--AUTORI: RICCIO GIUSEPPE N46004297
	  ROMANO ANTONIO  N46004321
--DESCRIZIONE: GUIDA ALLA LETTURA DEI DATI CON QUERY

--1-Analisi del contagio compilato su base regionale del 25 Marzo
SELECT *
FROM REGIONI_COVID19
WHERE DATA ='2020-03-25T17:00:00'
ORDER BY DENOMINAZIONE_REGIONE ASC ;

--2-Deceduti nella giornata del 25 Marzo
SELECT sum(DECEDUTI) AS TOTALE_DECEDUTI
FROM REGIONI_COVID19
WHERE DATA ='2020-03-25T17:00:00'
ORDER BY DENOMINAZIONE_REGIONE ASC ;

--3-Totale positivi alla giornata del 25 Marzo
SELECT sum(TOTALE_POSITIVI) AS TOTALE_ATTUALMENTE_POSITIVI
FROM REGIONI_COVID19
WHERE DATA ='2020-03-25T17:00:00'
ORDER BY DENOMINAZIONE_REGIONE ASC ;