--UNIVERSITA' DEGLI STUDI DI NAPOLI FEDERICO II
--FACOLTA' DI INGEGNERIA INFORMATICA
--ANNO ACCADEMICO 2019/20
--AUTORI: RICCIO GIUSEPPE N46004297
	  ROMANO ANTONIO  N46004321
--DESCRIZIONE: QUERY UTILI ALL'ANALISI DEI DATI PRESENTI NEL DATABASE

--5.1.1-Andamento completo dell'epidemia
SELECT DATA, sum(TOTALE_OSPEDALIZZATI) AS TOT_OSP, sum(TOTALE_POSITIVI) AS Tot_pos, sum(TOTALE_CASI) AS Tot_cas, sum(DECEDUTI) AS Tot_deceduti, sum(DIMESSI_GUARITI) AS Tot_dim
FROM REGIONI_COVID19
GROUP BY DATA
ORDER BY DATA ASC ;

--5.1.2-Contagi per Provincia in un determinato arco temporale (escluse quelle con dicitura 'In fase di definizione/aggiornamento')
SELECT DENOMINAZIONE_PROVINCIA, sum (TOTALE_CASI) AS Totale_Casi
FROM PROVINCE_COVID19 P JOIN PROVINCE P2 ON P.CODICE_PROVINCIA = P2.CODICE_PROVINCIA
WHERE data_REG <= '2020-03-25T17:00:00' AND data_REG >= '2020-03-19T17:00:00' AND DENOMINAZIONE_PROVINCIA <> 'In fase di definizione/aggiornamento'
GROUP BY DENOMINAZIONE_PROVINCIA
ORDER BY TOTALE_CASI DESC ;

--5.1.3-Regione con il maggior numero di casi per densità abitativa
SELECT * FROM ( SELECT R.DENOMINAZIONE_REGIONE, sum(R.TOTALE_CASI) AS TOTALE_CASI, R2.DENSITÀ_SUP AS DENSITÀ_ABITATIVA_IN_KM2
                FROM REGIONI_COVID19 R JOIN REGIONI R2 ON R.CODICE_REGIONE = R2.CODICE_REGIONE and R.DENOMINAZIONE_REGIONE = R2.DENOMINAZIONE_REGIONE
                GROUP BY R.DENOMINAZIONE_REGIONE, R2.DENSITÀ_SUP
                ORDER BY R2.DENSITÀ_SUP,TOTALE_CASI DESC )
WHERE ROWNUM = 1 ;

--5.1.4-Tamponi giornalieri e contagiati
SELECT DENOMINAZIONE_REGIONE, TAMPONI, TOTALE_POSITIVI
FROM REGIONI_COVID19
WHERE  DATA ='2020-05-03T17:00:00' ORDER BY TOTALE_POSITIVI DESC ;

--Classifiche
--5.1.5-Le 5 Regioni con più decessi fino al 3 Maggio
SELECT * FROM ( SELECT DENOMINAZIONE_REGIONE, DECEDUTI
                FROM REGIONI_COVID19
                WHERE  DATA ='2020-05-03T17:00:00' ORDER BY DECEDUTI DESC )
WHERE ROWNUM <= 5 ;

--5.1.6-Le 5 Regioni con meno decessi fino al 3 Maggio
SELECT * FROM ( SELECT DENOMINAZIONE_REGIONE, DECEDUTI
                FROM REGIONI_COVID19
                WHERE  DATA ='2020-05-03T17:00:00' ORDER BY DECEDUTI ASC )
WHERE ROWNUM <= 5 ;

--5.1.7-Le 10 Province con più casi fino al 3 Maggio
SELECT * FROM ( SELECT DENOMINAZIONE_PROVINCIA, R.DENOMINAZIONE_REGIONE, TOTALE_CASI
                FROM (PROVINCE_COVID19 P JOIN PROVINCE P2 ON P.CODICE_PROVINCIA = P2.CODICE_PROVINCIA)  JOIN REGIONI R ON P2.CODICE_REGIONE = R.CODICE_REGIONE
                WHERE DATA_REG ='2020-05-03T17:00:00' ORDER BY TOTALE_CASI DESC )
WHERE ROWNUM <= 10 ;

--5.1.8-Le 10 Province con meno casi fino al 3 Maggio
SELECT * FROM ( SELECT DENOMINAZIONE_PROVINCIA, R.DENOMINAZIONE_REGIONE, TOTALE_CASI
                FROM (PROVINCE_COVID19 P JOIN PROVINCE P2 ON P.CODICE_PROVINCIA = P2.CODICE_PROVINCIA)  JOIN REGIONI R ON P2.CODICE_REGIONE = R.CODICE_REGIONE
                WHERE DATA_REG ='2020-05-03T17:00:00' AND DENOMINAZIONE_PROVINCIA <> 'In fase di definizione/aggiornamento'
                ORDER BY TOTALE_CASI ASC )
WHERE ROWNUM <= 10 ;

--5.1.9-Andamento terapia intensiva, ricoverati con sintomi per regioni
SELECT DENOMINAZIONE_REGIONE, TERAPIA_INTENSIVA, RICOVERATI_CON_SINTOMI
FROM REGIONI_COVID19
WHERE DATA ='2020-05-03T17:00:00'
ORDER BY TERAPIA_INTENSIVA DESC ;

--5.2.0-Contagi nel mondo dall'1 Gennaio al 3 Maggio
SELECT DENOMINAZIONI_STATO, sum(CASI) AS TOTALE_CASI
FROM STATI_COVID19
GROUP BY DENOMINAZIONI_STATO
ORDER BY TOTALE_CASI DESC ;

--5.2.1-Contagi nei continenti dall'1 Gennaio al 3 Maggio
SELECT CONTINENTE, sum(CASI) AS TOTALE_CASI
FROM STATI_COVID19
GROUP BY CONTINENTE
ORDER BY TOTALE_CASI DESC ;

--5.2.2-I primi 10 stati con più casi dall'1 Gennaio al 3 Maggio
SELECT * FROM ( SELECT DENOMINAZIONI_STATO, sum(CASI) AS TOTALE_CASI
		FROM STATI_COVID19
		GROUP BY DENOMINAZIONI_STATO
		ORDER BY TOTALE_CASI DESC )
WHERE ROWNUM <= 10 ;

--5.2.3-Classifica dei continenti con più casi
SELECT CONTINENTE, sum(CASI) AS TOTALE_CASI
FROM STATI_COVID19
GROUP BY CONTINENTE
ORDER BY TOTALE_CASI DESC ;